# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d09e03044ec4206bf7672155a5a69a4b5b47d26ede2a19ad9455466087c2298ddc8780510c4bf647cded9cd3b9383406fa829cae5ed05cf2738cf2a342b105a

test:
  secret_key_base: 7382c83703ac838328c85cb301c9a39775e5ba5ee095138abb640eddda7658d3d7dce766207df48fa92d1f70002c5576f2d0276b1203bc8435b8500945cb7314

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
